sudo: required

dist: bionic

osx_image: xcode11

os:
- linux
- osx
- windows
language: cpp
compiler: gcc
notifications:
  email:
    recipients:
    - giadaloopmachine@gmail.com
    on_success: never
    on_failure: always

before_install:
- "./.travis/before_install.sh"

install:
- "./.travis/install.sh"

before_script:
- "./.travis/before_script.sh"

script: 
- "./.travis/script.sh" 

after_success:
- "./.travis/after_success.sh" 

# If build+test are successful, deploy the artifacts from dist/ dir (created in 
# after_success.sh) to S3. Only tagged releases on master are built.

deploy:
  provider: s3
  access_key_id: AKIAJP2CDHVGCPZAJGSA
  secret_access_key:
    secure: VNheuPP1d72MzX3FqJek8diglJllnpU4dS38eVMsHoLIbynlKwGFo35lBJ11xBK5RyoxCYy4Ka9kNifWulGVmfVOKYWhj39w91xl2D4HgPf/RcaCTvBmfg/mrhtop3Ns+WjYYVoxW2K5xmShdknS7HID9ldDBiKhafHNFWhyBWE=
  bucket: static.giadamusic.com
  skip_cleanup: true
  acl: public_read
  on:
    tags: false          # true
    branch: "travis-windows"    # "master"
  local_dir: dist
